# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routeguide/route_guide.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'routeguide/route_guide.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1crouteguide/route_guide.proto\x12\nrouteguide\"K\n\tinputData\x12\n\n\x02ID\x18\x01 \x01(\x03\x12\x11\n\tEventType\x18\x02 \x01(\t\x12\r\n\x05Price\x18\x03 \x01(\t\x12\x10\n\x08Quantity\x18\x04 \x01(\t\"\x1c\n\noutputData\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x32K\n\nRouteGuide\x12=\n\x08SendData\x12\x15.routeguide.inputData\x1a\x16.routeguide.outputData(\x01\x30\x01\x42\x16Z\x14\x41pexTrade/routeguideb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routeguide.route_guide_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\024ApexTrade/routeguide'
  _globals['_INPUTDATA']._serialized_start=44
  _globals['_INPUTDATA']._serialized_end=119
  _globals['_OUTPUTDATA']._serialized_start=121
  _globals['_OUTPUTDATA']._serialized_end=149
  _globals['_ROUTEGUIDE']._serialized_start=151
  _globals['_ROUTEGUIDE']._serialized_end=226
# @@protoc_insertion_point(module_scope)
