// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: routeguide/route_guide.proto

package routeguide

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=EventType,proto3" json:"EventType,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=Price,proto3" json:"Price,omitempty"`
	Quantity      string                 `protobuf:"bytes,4,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputData) Reset() {
	*x = InputData{}
	mi := &file_routeguide_route_guide_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputData) ProtoMessage() {}

func (x *InputData) ProtoReflect() protoreflect.Message {
	mi := &file_routeguide_route_guide_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputData.ProtoReflect.Descriptor instead.
func (*InputData) Descriptor() ([]byte, []int) {
	return file_routeguide_route_guide_proto_rawDescGZIP(), []int{0}
}

func (x *InputData) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *InputData) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *InputData) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *InputData) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type OutputData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        int32                  `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputData) Reset() {
	*x = OutputData{}
	mi := &file_routeguide_route_guide_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputData) ProtoMessage() {}

func (x *OutputData) ProtoReflect() protoreflect.Message {
	mi := &file_routeguide_route_guide_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputData.ProtoReflect.Descriptor instead.
func (*OutputData) Descriptor() ([]byte, []int) {
	return file_routeguide_route_guide_proto_rawDescGZIP(), []int{1}
}

func (x *OutputData) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

var File_routeguide_route_guide_proto protoreflect.FileDescriptor

const file_routeguide_route_guide_proto_rawDesc = "" +
	"\n" +
	"\x1crouteguide/route_guide.proto\x12\n" +
	"routeguide\"k\n" +
	"\tinputData\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x1c\n" +
	"\tEventType\x18\x02 \x01(\tR\tEventType\x12\x14\n" +
	"\x05Price\x18\x03 \x01(\tR\x05Price\x12\x1a\n" +
	"\bQuantity\x18\x04 \x01(\tR\bQuantity\"$\n" +
	"\n" +
	"outputData\x12\x16\n" +
	"\x06action\x18\x01 \x01(\x05R\x06action2K\n" +
	"\n" +
	"RouteGuide\x12=\n" +
	"\bSendData\x12\x15.routeguide.inputData\x1a\x16.routeguide.outputData(\x010\x01B\x16Z\x14ApexTrade/routeguideb\x06proto3"

var (
	file_routeguide_route_guide_proto_rawDescOnce sync.Once
	file_routeguide_route_guide_proto_rawDescData []byte
)

func file_routeguide_route_guide_proto_rawDescGZIP() []byte {
	file_routeguide_route_guide_proto_rawDescOnce.Do(func() {
		file_routeguide_route_guide_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeguide_route_guide_proto_rawDesc), len(file_routeguide_route_guide_proto_rawDesc)))
	})
	return file_routeguide_route_guide_proto_rawDescData
}

var file_routeguide_route_guide_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_routeguide_route_guide_proto_goTypes = []any{
	(*InputData)(nil),  // 0: routeguide.inputData
	(*OutputData)(nil), // 1: routeguide.outputData
}
var file_routeguide_route_guide_proto_depIdxs = []int32{
	0, // 0: routeguide.RouteGuide.SendData:input_type -> routeguide.inputData
	1, // 1: routeguide.RouteGuide.SendData:output_type -> routeguide.outputData
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_routeguide_route_guide_proto_init() }
func file_routeguide_route_guide_proto_init() {
	if File_routeguide_route_guide_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeguide_route_guide_proto_rawDesc), len(file_routeguide_route_guide_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routeguide_route_guide_proto_goTypes,
		DependencyIndexes: file_routeguide_route_guide_proto_depIdxs,
		MessageInfos:      file_routeguide_route_guide_proto_msgTypes,
	}.Build()
	File_routeguide_route_guide_proto = out.File
	file_routeguide_route_guide_proto_goTypes = nil
	file_routeguide_route_guide_proto_depIdxs = nil
}
